### ISSUE TITLE
Uncaught Error: Class "WP_Widget" not found

### ISSUE THREAD

**Issue by artschekoff** [php-stubs/woocommerce-stubs#27]
# Config

```includes:
includes:
    - vendor/phpstan/phpstan/conf/bleedingEdge.neon
    - vendor/szepeviktor/phpstan-wordpress/extension.neon
    - vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php
parameters:
	level: 6
	paths:
		- src
	scanDirectories:
	    - ../
```

# Error:

```
PHP Fatal error:  Uncaught Error: Class "WP_Widget" not found in /private/var/www/xbox.local.com/api/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php:5972
Stack trace:
#0 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Adapters/PhpAdapter.php(22): require()
#1 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(36): _PHPStan_eb6a95a92\Nette\DI\Config\Adapters\PhpAdapter->load('/private/var/ww...')
#2 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_eb6a95a92\Nette\DI\Config\Loader->load('/private/var/ww...', NULL)
#3 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(43): PHPStan\DependencyInjection\NeonLoader->load('/private/var/ww...', NULL)
#4 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_eb6a95a92\Nette\DI\Config\Loader->load('/private/var/ww...', NULL)
#5 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(188): PHPStan\DependencyInjection\NeonLoader->load('/private/var/ww...', NULL)
#6 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(132): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput), Array, '1G', NULL, Array, '/private/var/ww...', NULL, NULL, false, true)
#7 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_eb6a95a92\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRun(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(127): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->run()
#12 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(128): _PHPStan_eb6a95a92\{closure}()
#13 /private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan(8): require('phar:///private...')
#14 /private/var/www/xbox.local.com/api/vendor/bin/phpstan(119): include('/private/var/ww...')
#15 {main}
  thrown in /private/var/www/xbox.local.com/api/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php on line 5972
Fatal error: Uncaught Error: Class "WP_Widget" not found in /private/var/www/xbox.local.com/api/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php:5972
Stack trace:
#0 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Adapters/PhpAdapter.php(22): require()
#1 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(36): _PHPStan_eb6a95a92\Nette\DI\Config\Adapters\PhpAdapter->load('/private/var/ww...')
#2 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_eb6a95a92\Nette\DI\Config\Loader->load('/private/var/ww...', NULL)
#3 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/nette/di/src/DI/Config/Loader.php(43): PHPStan\DependencyInjection\NeonLoader->load('/private/var/ww...', NULL)
#4 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/DependencyInjection/NeonLoader.php(29): _PHPStan_eb6a95a92\Nette\DI\Config\Loader->load('/private/var/ww...', NULL)
#5 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/Command/CommandHelper.php(188): PHPStan\DependencyInjection\NeonLoader->load('/private/var/ww...', NULL)
#6 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/src/Command/AnalyseCommand.php(132): PHPStan\Command\CommandHelper::begin(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput), Array, '1G', NULL, Array, '/private/var/ww...', NULL, NULL, false, true)
#7 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Command/Command.php(259): PHPStan\Command\AnalyseCommand->execute(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(870): _PHPStan_eb6a95a92\Symfony\Component\Console\Command\Command->run(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(261): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRunCommand(Object(PHPStan\Command\AnalyseCommand), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/vendor/symfony/console/Application.php(157): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->doRun(Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Input\ArgvInput), Object(_PHPStan_eb6a95a92\Symfony\Component\Console\Output\ConsoleOutput))
#11 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(127): _PHPStan_eb6a95a92\Symfony\Component\Console\Application->run()
#12 phar:///private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan.phar/bin/phpstan(128): _PHPStan_eb6a95a92\{closure}()
#13 /private/var/www/xbox.local.com/api/vendor/phpstan/phpstan/phpstan(8): require('phar:///private...')
#14 /private/var/www/xbox.local.com/api/vendor/bin/phpstan(119): include('/private/var/ww...')
#15 {main}
  thrown in /private/var/www/xbox.local.com/api/vendor/php-stubs/woocommerce-stubs/woocommerce-stubs.php on line 5972
make: *** [lint] Error 255

```

**Comment by szepeviktor** [comment]
Hello @DreadfulBot 👋🏻 

Your config above looks strange.
Could you doublecheck it?

**Comment by artschekoff** [comment]
> Hello @DreadfulBot 👋🏻
> 
> Your config file looks strange. Could you doublecheck it?

Hello!

Updated.

Originally there was scanDirectories to folder where wordpress is installed, but trying to replace it with stubs now

**Comment by szepeviktor** [comment]
Here is how to install WC stubs: https://github.com/php-stubs/woocommerce-stubs/blob/master/README.md#usage-in-phpstan

**Comment by szepeviktor** [comment]
WP core stubs are included in `szepeviktor/phpstan-wordpress`

**Comment by artschekoff** [comment]
Oh sorry, my bad. Tried to add to includes, but had to parameters -> bootstrapFiles. Now works, thanks a lot! @szepeviktor
